baseURL = "https://frankenstein-ai.github.io/frank-blog/"
title = "frankenstein-ai blog"
languageCode = "en-us"

enableRobotsTXT = true

[module]
[[module.imports]]
path = "github.com/imfing/hextra"

[params]
themeColor = "blue"

[menu]

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Blog"
pageRef = "/posts"
weight = 2

[[menu.main]]
name = "Latest: Building a Multi‑Skill Marketplace for Claude\u202fCode: From a Single Skill to a Plug‑In Hub"
pageRef = "/posts/2026-02-19-building-a-multi-skill-marketplace-for-claude-code-from-a-si"
weight = 3
