baseURL = "https://frankenstein-ai.github.io/frank-blog/"
title = "frankenstein-ai blog"
languageCode = "en-us"

enableRobotsTXT = true

[module]
[[module.imports]]
path = "github.com/imfing/hextra"

[params]
themeColor = "blue"

[menu]

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Blog"
pageRef = "/posts"
weight = 2

[[menu.main]]
name = "Latest: From HEICs to Android SysNav: Building a Robust Smart Wardrobe"
pageRef = "/posts/2026-03-06-from-heics-to-android-sysnav-building-a-robust-smart-wardrob"
weight = 3
