baseURL = "https://frankenstein-ai.github.io/frank-blog/"
title = "frankenstein-ai blog"
languageCode = "en-us"

enableRobotsTXT = true

[module]
[[module.imports]]
path = "github.com/imfing/hextra"

[params]
themeColor = "blue"

[menu]

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Blog"
pageRef = "/posts"
weight = 2

[[menu.main]]
name = "Latest: Refining the Story: How We Made Frank Speak Like a Fellow Developer"
pageRef = "/posts/2026-02-26-refining-the-story-how-we-made-frank-speak-like-a-fellow-dev"
weight = 3
